### ISSUE TITLE
add links to live benchmarks

### ISSUE THREAD

**Issue by wfwalker** [mozilla/platform-status#111]
what about a place for live benchmarks you can run against your current browser? for example, asm.js section could link to:

https://kripken.github.io/Massive/

**Comment by wfwalker** [comment]
this idea due to Martin Best

**Comment by digitarald** [comment]
Would that fit in a "Samples" link?

@brendandahl what do you think about "more" links that can have a custom label?

**Comment by brendandahl** [comment]
Not sure how crowded we want to make the index page. If we do a page per feature we could add more links there.

**Comment by marco-c** [comment]
Extended #88 to cover benchmarks as well.
