### ISSUE TITLE
Periodically update feature data

### ISSUE THREAD

**Issue by marco-c** [mozilla/platform-status#223]
We could end up with stale data, as reported in #189.

**Comment by digitarald** [comment]
My proposal:

- build step gets the latest modified time for the status files it pulled and saves this to a file
- express that serves the static page checks the status URLs (head request) once a day to get the last modified dates
- if the stored last modified time is older than the checked times, execute `gulp build`

**Comment by digitarald** [comment]
We will need this for push - thoughts on my proposal @brendandahl @zalun ?

**Comment by digitarald** [comment]
I will go ahead and add this, running the build job every 4 hours to start with, together with #293 for more intelligent caching.

**Comment by zalun** [comment]
I've added a scheduler - https://scheduler.heroku.com/dashboard

**Comment by digitarald** [comment]
The scheduler hits the cache and will not actually get new data until #293 is fixed

**Comment by marco-c** [comment]
#293 has been fixed, so we can close this.
