### ISSUE TITLE
Define measurable success goals

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#27]
Spawned off #13 …

via @dbialer:

> I think it would be good to build product KPIs directly into this so that we have a clear understanding of what success looks like and measure from the start. We should instrument and build measurability directly into the MVP with Github, feedback mechanisms, and perhaps analytics. These could include:
- a.  Page/project visits as an indicator of interest in this project and usage. We should have a goal of X visits per month as an indicator of usage. What is a reasonable goal here? 5K visits per month?
- b. community participation - how many non-paid staff contributors join this (as one of the goals is to increase radical participation). We should have a goal of Y contributors by Z date. Perhaps pull requests or commits? How would 5-10 contributors (outside paid staff) by sometime in Q1?
- c. Feedback - one of the goals is feedback. How do we collect that? filing issues? Can we have a feedback form? We should have a goal of some sort of active/useful feedback. Not sure what would be good here.
- d. How do we know it is low maintenance? We should have a goal that other teams are updating their information around X features.

> If we don't achieve goals that get us on the right track, then perhaps this isn't as useful as we think? So part of this project should not just be coding, but achieving the usage we desire.

> Any thoughts on this?

Re: @TimAl

> > We should have a goal of X visits per month as an indicator of usage
> 
> Sounds good to me. I have no idea what a reasonable number would be... I also don't really know _when_ it would be reasonable to expect usage to pick up.
> 
> > We should have a goal of Y contributors by Z date. Perhaps pull requests or commits? How would 5-10 contributors (outside paid staff) by sometime in Q1?
> 
> I like the idea of making contribution a goal. These numbers sound optimistic to me but I don't know if this project will turn out to be more "if you build it they will come" or "if you start building it they will come and help out"
> 
> > Feedback - one of the goals is feedback. How do we collect that? filing issues? Can we have a feedback form? We should have a goal of some sort of active/useful feedback. Not sure what would be good here.
> 
> Good points/questions. We should probably file an issue for this and continue the discussion there.
> 
> > How do we know it is low maintenance?
> 
> This seems like a hugely important piece of the project. If it's not low-maintenace then eventually it will fizzle. Maybe a UX person can help us with this? Measure the number of clicks to update something? Measure the number of manual tasks? This also seems like a good candidate for a separate issue where we can discuss
> 
> > So part of this project should not just be coding, but achieving the usage we desire
> 
> I totally agree with this message

**Comment by digitarald** [comment]
We'll add analytics for now, not marking this blocking for launch.

**Comment by marco-c** [comment]
I guess we can close this now.
