### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#28]
Add analytics before launch to measure project success against goals from #27.

We also want to track usage to understand users and their use cases.

**Comment by dbialer** [comment]
I suggest we add can use Traffic (though I can't view this)
https://github.com/blog/1672-introducing-github-traffic-analytics 
   - unique visitors (within 3 months of launch, 200 per month?)
and #contributors (non-paid employee)
  - within 3 months of launch, 3 contributors (no idea of that is optimistic or pessimistic), but a goal is 'radical participation'.  Also not sure if we can expect non-employee contributors for this particular project given the nature of it as a reporting tool.
and visits to site (not the code repo, but the site itself).  Perhaps we need Google Analytics on this page?
Launch is the first week of functional public release.

**Comment by dbialer** [comment]
We should add a GA code but this will be dependent on the hosting.  Once we have that we will get an ID from GA ops and have it set up.

**Comment by digitarald** [comment]
We got a tracking id, need to add it.

**Comment by chrismore** [comment]
@digitarald @dbialer please file a bug here to get a GA ID in Mozilla's GA premium service: https://bugzilla.mozilla.org/enter_bug.cgi?product=Websites&component=Web%20Analytics and assign the bug to :garethc in bugzilla. He'll get you setup asap.

**Comment by marco-c** [comment]
@digitarald I guess this was done, but it isn't properly working? (#332).

**Comment by digitarald** [comment]
Its working, ga just wants to see a 100% match on its snippet (which I changed to work with out linting).
