### ISSUE TITLE
Make CONTRIBUTING.md clearer about the bugzilla field

### ISSUE THREAD

**Issue by marco-c** [mozilla/platform-status#282]
See #279.

**Comment by digitarald** [comment]
Supporting multiple bugs seems to be the way forward, as it is useful in the case of the referenced bug. Thoughts, @brendandahl ?

**Comment by brendandahl** [comment]
Or we get people to make a proper meta bug.

**Comment by digitarald** [comment]
That would be best practice, I agree. Platform's Trello board also has a
list of bugs for some features that it's tracking for target platform
fields. I will check how common that is.

On Wednesday, January 27, 2016, Brendan Dahl <notifications@github.com>
wrote:

> Or we get people to make a proper meta bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/platatus/issues/282#issuecomment-175776844>.
>


-- 
Web Craftsman | harald@mozilla.com | @digitarald [skype/irc/line] |
+1-650-963-6612 [wapp/telegram]
