### ISSUE TITLE
Obey caching headers for update requests

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#293]
Today we got a few `Error: Wrong value for chrome_ref in offscreencanvas.md` in the channel because the Google's status JSON updated but the old file was used from the cache.

This could be circumvented when the caching used in the build would be aware of HTTP caching headers in the web responses.

**Comment by digitarald** [comment]
Thoughts @marco-c @TimAbraldes ?

**Comment by TimAbraldes** [comment]
> This could be circumvented when the caching used in the build would be aware of HTTP caching headers in the web responses.

Seems reasonable. We'll store some metadata (e.g. expiration time) with each file and make the files expire based on what the cache headers tell us

**Comment by digitarald** [comment]
I'd leave that yak unshaven as its cold outside. This looks promising: https://www.npmjs.com/package/eu but the search for cache-header-aware request libraries is littered with elderly or half-shaved yaks.

**Comment by zalun** [comment]
I'm trying eu, but I've got a hard time with closing the link to database. Seems like it should be open and closed on every request. This lib is prepared for servers...

**Comment by zalun** [comment]
Please review the #376

**Comment by marco-c** [comment]
Fixed by #376.
