### ISSUE TITLE
New chrome status: "In experimental framework"

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#307]
It might be the new way to ship APIs quickly for everybody. https://github.com/jpchase/ExperimentalFramework/blob/master/explainer.md

Bluetooth ships in 50 as experiment: https://www.chromestatus.com/feature/5264933985976320

This also breaks our builds as we validate status texts.

**Comment by marco-c** [comment]
Do we want to show the experimental features in a different way than "DEVELOPING"?

**Comment by digitarald** [comment]
No, this should be fixed now with my patch.
