### ISSUE TITLE
google analytics says missing code for homepage

### ISSUE THREAD

**Issue by wfwalker** [mozilla/platform-status#332]
"No valid tracking code found for property platform-status.mozilla.org's default URL https://platform-status.mozilla.org."

**Comment by zalun** [comment]
`window.ga` is a function - what else can we check about it?

**Comment by darkwing** [comment]
I see the analytics file there but I don't see the `create` call or the `sendpageview` call. From my site:

```
ga("create",'ANALYTICS_ID_HERE');
ga("send","pageview")
```

**Comment by darkwing** [comment]
This; https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet

**Comment by zalun** [comment]
https://github.com/mozilla/platatus/blob/master/src/js/index.js#L55

**Comment by zalun** [comment]
@wfwalker is it still a problem (not that it have been fixed, but I see it in bundle.js).
Does it need to be in index.html?

**Comment by wfwalker** [comment]
Here are the details from the google analytics dashboard:

```
Missing Tracking Code
First seen time: Jan 15, 2016 4:46:12 AM
Last seen time: Mar 15, 2016 4:32:47 AM
No valid tracking code found for property platform-status.mozilla.org's default URL https://platform-status.mozilla.org. Make sure your pages are tagged with a supported version of the tracking code.

Google Tag Assistant Recordings can help you ensure that your pages are properly tagged.
Learn more: https://support.google.com/analytics/bin/answer.py?answer=1086338&hl=en_US
```

**Comment by zalun** [comment]
What is the anayltics ID?

**Comment by digitarald** [comment]
Tracking works. I changed the snippet to work with out linting: https://github.com/mozilla/platform-status/blob/4aaac7814b1c4af846e3d99693050c14be19bcff/src/js/index.js#L55
