### ISSUE TITLE
Consider using the Webkit logo

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#333]
The logo right now is hard to decipher in its small size and most people don't have Webkit Nightly installed or even know about it. The solution could be to use the new WebKit logo

![Webkit Logo](https://webkit.org/wp-content/themes/webkit/images/webkit.svg)

**Comment by marco-c** [comment]
The WebKit Nightly logo looks similar to the Safari one (it's just different colors), but I'm OK with switching if you think this one is more clear.

Let's also see what we decide in https://github.com/mozilla/platatus/issues/324, we could use the WebKit Nightly logo for in-development features and this one for released features.

**Comment by marco-c** [comment]
Close in favor of #409?
