### ISSUE TITLE
Build on heroku fails with "max number of clients reached" for redis

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#393]
https://dashboard.heroku.com/apps/platatus/activity/builds/3ec6a544-d305-472d-b701-832e797b7c87

Tried some fixes in 4aaac7814b1c4af846e3d99693050c14be19bcff, we seem to have too many connections open during the `build` task since the `eu` addition .

**Comment by digitarald** [comment]
This made travis fail, continue to investigate: https://travis-ci.org/mozilla/platatus/builds/119117576

**Comment by digitarald** [comment]
We should check to use a single redis connection. What's blocking this atm, @zalun ?

**Comment by digitarald** [comment]
Maybe a hint in https://github.com/NodeRedis/node_redis/issues/247#issuecomment-47945348

**Comment by zalun** [comment]
might happen that some connection isn't closed and another is opened during that time. I'll check it a little closer - there was no issue before though (I mean tests on routes were performing fine).

**Comment by digitarald** [comment]
Tests and builds work locally.

Even after d19cecd travis still fails now with `Redis connection gone from end event.`: https://travis-ci.org/mozilla/platatus

**Comment by zalun** [comment]
Is there a way to try it somehow without creating fake pull requests?

**Comment by digitarald** [comment]
We can also disable that heroku pulls from github when travis is done

**Comment by digitarald** [comment]
@zalun we can also experiment on a branch and build that on heroku

**Comment by BridgeAR** [comment]
> We should check to use a single redis connection. What's blocking this atm, @zalun ?

I also recommend not using more connections than you definitely have to use. By using a new client each time you need a query, the performance of Redis is degraded a lot.

If you use pub sub or blocking commands (e.g. with a queue) it is of course fine to use more clients (and you likely should), but for a cache call this is not necessary.

**Comment by digitarald** [comment]
Fixed in #212
