### ISSUE TITLE
Change Webkit to Safari, using Safari Technology Preview

### ISSUE THREAD

**Issue by digitarald** [mozilla/platform-status#409]
Chatted with [jonathandavis](https://twitter.com/jonathandavis) and it should make it more recognizable than Webkit, as no other browsers are represented by their engine.

https://developer.apple.com/safari/technology-preview/

Icons: https://github.com/alrra/browser-logos/tree/master/safari-technology-preview

**Comment by marco-c** [comment]
The only problem is that this would mean reopening #189, as Safari might not support all features supported by WebKit.

**Comment by marco-c** [comment]
CC @BenjaminPoulain, who wrote https://github.com/MicrosoftEdge/Status/pull/226#issuecomment-97672727.

**Comment by BenjaminPoulain** [comment]
I am not sure what Jon meant. He is not here right now.
Safari Technology Preview ships features that are not ready for Safari since it takes a snapshot from WebKit ToT.

Maybe Jon just wanted to have the icon and name changed to give more visibility to Safari Preview instead of nightly...

**Comment by marco-c** [comment]
@BenjaminPoulain so, is representing WebKit status data with the Safari Technology Preview correct? Or does WebKit status data still contain something that isn't available in Safary Technology Preview?

**Comment by BenjaminPoulain** [comment]
@marco-c That sounds okay.
There might be minor differences but we'll try to keep Safary Technology Preview as close to WebKit as possible.

**Comment by marco-c** [comment]
Ok, thanks!
