### ISSUE TITLE
Safari Technology Preview has shipped Shodow DOM.

### ISSUE THREAD

**Issue by futursolo** [mozilla/platform-status#471]
The status of Shadow DOM for Safari Technology Preview should be changed to landed.

webkit-ref: https://webkit.org/status/#feature-shadow-dom

https://platform-status.mozilla.org/#shadow-dom

**Comment by marco-c** [comment]
Could you create a PR for this? You just need to update https://github.com/mozilla/platform-status/blob/master/features/shadow-dom.md.

**Comment by futursolo** [comment]
This [file](https://github.com/mozilla/platform-status/blame/master/features/shadow-dom.md#L11) already have the correct `title` property from https://svn.webkit.org/repository/webkit/trunk/Source/WebCore/features.json.

So do [Custom Elements](https://github.com/mozilla/platform-status/blame/master/features/custom-elements.md#L11).

But both of them are showing `No Signal` on the site.

Or maybe the `title` should be changed to `Web Components` like [HTML Templates](https://github.com/mozilla/platform-status/blame/master/features/html-templates.md#L8)?
WebKit has already supported All Web Components features except [HTML imports](https://webkit.org/status/#feature-html-imports).

**Comment by marco-c** [comment]
> This file already have the correct title property from https://svn.webkit.org/repository/webkit/trunk/Source/WebCore/features.json.

> So do Custom Elements.

> But both of them are showing No Signal on the site.

Sorry, I thought we didn't have the info about webkit in the md files. It looks like there's a bug somewhere.
