### ISSUE TITLE
Update webkit's font-display status to "developing"

### ISSUE THREAD

**Issue by notwaldorf** [mozilla/platform-status#483]
The current `font-display` status shows "no signals": https://webkit.org/status/#specification-css-font-display but the webkit.org status shows (an optimistic) "in development": https://webkit.org/status/#specification-css-font-display.

**Comment by marco-c** [comment]
Thanks for noticing this!
Fixing this kind of errors is really easy. If you want in the future you can submit PRs like https://github.com/mozilla/platform-status/pull/487.
