### ISSUE TITLE
Every shipped feature is now considered as in development

### ISSUE THREAD

**Issue by phistuck** [mozilla/platform-status#484]
However, I do not see any recent commit, so I guess the server was changed without committing it ?
It happened between 2017-8-28 and 2017-8-29 according to https://platformstatus.io/
![image](https://user-images.githubusercontent.com/184400/29858700-572a34d0-8d67-11e7-9ec4-c36d340e5979.png)

**Comment by marco-c** [comment]
There must be a bug somewhere. The code of the server has not been changed.
