### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by stefanjudis** [mozilla/platform-status#509]
Hello. 👋🏻

Just noticed the search is broken (tested Chrome and FF). :)

<img width="1438" alt="screen shot 2017-12-20 at 23 59 05" src="https://user-images.githubusercontent.com/962099/34232707-d703a98e-e5e1-11e7-9ce2-86193abf0793.png">

I wanted to fix it myself but am running in setup issues (#510).

**Comment by Schweinepriester** [comment]
+1
