### ISSUE TITLE
All edge links broken

### ISSUE THREAD

**Issue by doublah** [mozilla/platform-status#517]
dev.modern.ie appears to be dead, with no redirect.
Current (dead) links are in format https://dev.modern.ie/platform/status/<feature>
New links are in format https://developer.microsoft.com/en-us/microsoft-edge/platform/status/<feature>/

Example: https://platform-status.mozilla.org/#background-sync links to https://dev.modern.ie/platform/status/backgroundsyncapi (dead link), should link to https://developer.microsoft.com/en-us/microsoft-edge/platform/status/backgroundsyncapi/

Relevant lines: https://github.com/mozilla/platform-status/blob/511bd7b876dc89bd447ea6393cd67d448abc870d/engine/index.js#L135-L145

**Comment by marco-c** [comment]
@doublah sounds like you have all the info and also found the code, would you mind writing a PR?
