### ISSUE TITLE
font-variation-settings display as shipped in Firefox even if they aren't (at least on Windows)

### ISSUE THREAD

**Issue by xlf1024** [mozilla/platform-status#519]
[https://platform-status.mozilla.org/#css-font-variation-settings](https://platform-status.mozilla.org/#css-font-variation-settings) says font-variation-settings were shipped in Firefox, Version 53, but:

Visiting [https://v-fonts.com/](https://v-fonts.com/), the browser console displays `Unknown property ‘font-variation-settings’.  Declaration dropped.` in FF 58.0.2, 64 bit on Win10 v1709.

the Discussion in [the corresponding meta bug in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1302685) looks like it only works on OSX yet.

**Comment by chrisdavidmills** [comment]
Confirmed. I think it makes sense to update this to "in development" on Firefox. I've submitted a PR to do that.
