### ISSUE TITLE
Data for the Abort API is wrong

### ISSUE THREAD

**Issue by stof** [mozilla/platform-status#535]
https://platform-status.mozilla.org/#abort-api marks the feature as landed in firefox, and no signals in any other browsers. But according to https://www.chromestatus.com/features/5631483679080448 and https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Browser_compatibility it is already shipped in all browsers.

**Comment by chrisdavidmills** [comment]
We've updated the platform-status app, so at this point you should see a change in the data. It still says no signals for Edge, but the MDN page contradicts this. I can't find an entry about it in dev.windows.com, but I will keep investigating this.

Thanks for reporting!

**Comment by stof** [comment]
Yeah, I was not able to find the `ie_ref` for it when updating the info.

Caniuse and BCD are both marking it as shipped in Edge, but the Caniuse info is not used to mark it as landed, and BCD is not used at all (that's #534)
