### ISSUE TITLE
Changes are not online

### ISSUE THREAD

**Issue by SebastianZ** [mozilla/platform-status#587]
The changes added to this repository since last December are not visible online!

As far as I can see, the earliest addition [not shown online](https://platform-status.mozilla.org/) is the one from https://github.com/mozilla/platform-status/commit/fd83dea8b72650f89ee9eb88bd0d666aa66c16b7.

I guess somebody just needs to make a pull on the live server. 😄 

Sebastian

**Comment by chrisdavidmills** [comment]
@digitarald how do I actually do this? I'd love to take over the running of this site properly, but I'm not really sure how it works.

**Comment by chrisdavidmills** [comment]
@digitarald thanks!

**Comment by chrisdavidmills** [comment]
@digitarald did you get a chance to look at this? It's not showing any changes from quite a while back.

**Comment by marco-c** [comment]
I've done a manual deployment. I don't have permissions to add you to the app, maybe you should file a bug to get permissions so you can manage deployments (and maybe enable automatic deployments).

**Comment by chrisdavidmills** [comment]
@marco-c I have no idea how to do any of this. What component do I file a bug under to do that? Could we have a short working session at some point so you can teach me how to do these things?

**Comment by digitarald** [comment]
@chrisdavidmills I am filing the right bugs to get you (and me again) heroku access. There we'll also flip the pref to make it automatic, linked to Github.

**Comment by chrisdavidmills** [comment]
@digitarald thanks so much; really appreciate it.
